# Shared helpers for Render CLI scripts (Windows PowerShell)

$Script:ProjectRoot = Split-Path -Parent $PSScriptRoot
$Script:ToolsDir = Join-Path $ProjectRoot ".tools\render"
$Script:RenderExe = Join-Path $ToolsDir "render.exe"
$Script:RenderVersion = "2.17.0"
$Script:RenderZipUrl = "https://github.com/render-oss/cli/releases/download/v2.17.0/cli_2.17.0_windows_amd64.zip"
$Script:DefaultServiceName = "music-api"
$Script:DefaultRepo = "https://github.com/TheSamurai4861/vibes--api.git"
$Script:StateFile = Join-Path $ProjectRoot ".render-state.json"
$Script:LocalEnvFile = Join-Path $ProjectRoot ".env.render.local"

function Get-RenderExe {
    if (-not (Test-Path $RenderExe)) {
        throw "Render CLI not found at $RenderExe. Run: .\scripts\render-install.ps1"
    }
    return $RenderExe
}

function Invoke-Render {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Args
    )
    $exe = Get-RenderExe
    $output = & $exe @Args 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw ($output | Out-String)
    }
    return $output
}

function Test-RenderAuth {
    $configPath = Join-Path $env:USERPROFILE ".render\cli.yaml"
    if (-not (Test-Path $configPath)) {
        return $false
    }
    try {
        $null = Invoke-Render -Args @("workspaces", "-o", "json", "--confirm")
        return $true
    } catch {
        # CLI config exists; allow setup to proceed (workspace may still be set)
        return $true
    }
}

function Ensure-RenderLogin {
    if (Test-RenderAuth) { return }
    Write-Host "Render CLI not authenticated. Run:" -ForegroundColor Yellow
    Write-Host "  .\scripts\render-install.ps1" -ForegroundColor Cyan
    Write-Host "  render login" -ForegroundColor Cyan
    Write-Host "  render workspace set" -ForegroundColor Cyan
    throw "Render authentication required."
}

function Get-OrCreateAdminToken {
    if ($env:ADMIN_TOKEN) { return $env:ADMIN_TOKEN }
    if (Test-Path $LocalEnvFile) {
        foreach ($line in Get-Content $LocalEnvFile) {
            if ($line -match '^\s*ADMIN_TOKEN=(.+)$') {
                return $matches[1].Trim()
            }
        }
    }
    $token = [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 }))
    @(
        "# Generated by render-setup.ps1 - do not commit",
        "ADMIN_TOKEN=$token"
    ) | Set-Content -Path $LocalEnvFile -Encoding UTF8
    Write-Host "ADMIN_TOKEN saved to .env.render.local (gitignored)" -ForegroundColor Green
    return $token
}

function Save-RenderState {
    param([hashtable]$Data)
    $merged = @{}
    if (Test-Path $StateFile) {
        $obj = Get-Content $StateFile -Raw | ConvertFrom-Json
        $obj.PSObject.Properties | ForEach-Object { $merged[$_.Name] = $_.Value }
    }
    foreach ($key in $Data.Keys) {
        $merged[$key] = $Data[$key]
    }
    [PSCustomObject]$merged | ConvertTo-Json -Depth 5 | Set-Content -Path $StateFile -Encoding UTF8
}

function Get-RenderState {
    if (-not (Test-Path $StateFile)) { return $null }
    return Get-Content $StateFile -Raw | ConvertFrom-Json
}

function Find-ServiceByName {
    param([string]$Name = $DefaultServiceName)
    $json = Invoke-Render -Args @("services", "-o", "json", "--confirm") | Out-String
    if ([string]::IsNullOrWhiteSpace($json) -or $json.Trim() -eq "null") {
        return $null
    }
    $services = $json | ConvertFrom-Json
    if ($services -isnot [array]) { $services = @($services) }
    foreach ($item in $services) {
        $svc = $item.service
        if ($svc -and $svc.name -eq $Name) {
            return $svc
        }
    }
    return $null
}

function Get-ServicePublicUrl {
    param($Service)
    if ($Service.serviceDetails -and $Service.serviceDetails.url) {
        return $Service.serviceDetails.url.TrimEnd('/')
    }
    if ($Service.url) {
        return $Service.url.TrimEnd('/')
    }
    return $null
}
